# Generated by Django 5.0.1 on 2024-01-06 07:39

import django.contrib.auth.password_validation
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MassRoleDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_num', models.CharField(max_length=15)),
                ('role_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long.'), django.core.validators.RegexValidator('[A-Z]', message='Password must contain at least one uppercase letter.'), django.core.validators.RegexValidator('[a-z]', message='Password must contain at least one lowercase letter.'), django.contrib.auth.password_validation.validate_password])),
                ('full_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+\\s[a-zA-Z]+$', message="Full name must be in the format 'FirstName LastName'.")])),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be 10 digits long and contain only numeric characters.')])),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Pincode must be 6 digits long and contain only numeric characters.')])),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='role_tye', to='task_app.massroledetailmodel')),
            ],
        ),
    ]
