# Generated by Django 5.0.1 on 2024-01-06 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_categorymodel_contentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_tye', to='task_app.registrationmodel'),
        ),
    ]
